apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gfz0fgkw0-python 
  janus-idp.io/tekton: gfz0fgkw0-python
  backstage.io/kubernetes-id: gfz0fgkw0-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gfz0fgkw0-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml